import os
import base64
import mimetypes
import pandas as pd
from dotenv import load_dotenv

load_dotenv(override=True, verbose=True)

METRICAS_CSV_PATH = '/app/backend/models/wound_metrics_report_FINETUNED.csv'
_METRICAS_DF = None

def _get_metricas_df():
    """Lazily loads the real metrics report generated during training"""
    global _METRICAS_DF
    if _METRICAS_DF is None:
        _METRICAS_DF = pd.read_csv(METRICAS_CSV_PATH, index_col=0)
    return _METRICAS_DF

def get_gemini_client():
    """
    Returns the Gemini client using google-genai
    """
    try:
        from google import genai

        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            raise ValueError("GEMINI_API_KEY not found")

        client = genai.Client(api_key=api_key)
        return client
    except ImportError:
        raise ImportError("google-genai library not installed")

def describe_image_with_analysis(image_path: str, dados_analise: dict):
    """
    Generates a detailed technical description of the image based on the model's analysis
    """
    try:
        client = get_gemini_client()
        
        with open(image_path, "rb") as f:
            image_data = f.read()
        
        classe_predita = dados_analise.get('classe_predita', 'Desconhecida')
        classe_traduzida = dados_analise.get('classe_traduzida', 'Desconhecida')
        confianca = dados_analise.get('confianca_predita_percentual', 'N/A')
        probabilidades = dados_analise.get('probabilidades_completas', {})

        metricas_df = _get_metricas_df()
        if classe_predita in metricas_df.index:
            metricas_classe = metricas_df.loc[classe_predita]
            precisao_str = f"{metricas_classe['precision']:.4f}"
            recall_str = f"{metricas_classe['recall']:.4f}"
            f1_str = f"{metricas_classe['f1-score']:.4f}"
        else:
            precisao_str = recall_str = f1_str = 'N/A'

        prompt = f"""
        You are a Clinical Decision Support Artificial Intelligence (CDSS) system specialized in the initial screening and classification of skin lesions. Your goal is to generate a concise PRELIMINARY TECHNICAL REPORT and RISK REPORT, using strictly medical language, to be read and validated by a specialist physician.

        INPUT INFORMATION FOR THE CLASSIFICATION MODEL (VGG16 Fine-Tuned):
        1. PREDICTED CLASS: {classe_predita} ({classe_traduzida}) - Confidence: {confianca}
        2. PROBABILITY VECTOR: {probabilidades}
        3. HISTORICAL MODEL METRICS FOR THE PREDICTED CLASS:
           - Precision: {precisao_str}
           - Recall: {recall_str}
           - F1-Score: {f1_str}

        REQUIRED INFORMATION FOR THE ANSWER (Do not exceed 300 words):

        * Identify the primary classification and the model confidence.
        * Justify. Describe the visual characteristics of the image that corroborate the classification {classe_predita} ({classe_traduzida}).
        * Perform a differential analysis. Comment on the 2-3 classes with the highest probability after the primary one, briefly explaining the similarities and differences.
        
        Format your response clearly and technically, using bullet points when appropriate, but never use titles. Only plain text and formatting such as bold, italics, lists, etc. No titles.

        Be formal and objective. NEVER USE TITLES OR SUBTITLES. NO H1, H2, H3, ETC.
        """

        from google.genai import types
        
        response = client.models.generate_content(
            model='gemini-2.5-flash-lite',
            contents=[
                prompt,
                types.Part.from_bytes(
                    data=image_data,
                    mime_type=mimetypes.guess_type(image_path)[0] or 'image/jpeg'
                )
            ]
        )
        
        return response.text.strip()
        
    except Exception as e:
        print(f"❌ Error generating image description: {e}")
        aviso_p = dados_analise.get('risco_p', {}).get('Aviso_P', '')
        return f"""
        **PRELIMINARY TECHNICAL REPORT - CLASSIFIED IMAGE**

        **Primary Classification:** {dados_analise.get('classe_predita', 'N/A')} ({dados_analise.get('classe_traduzida', 'N/A')})
        **Model Confidence:** {dados_analise.get('confianca_predita_percentual', 'N/A')}
        **Historical F1-Score:** {dados_analise.get('metrica_f1_classe_predita', 'N/A'):.4f}

        **Differential Analysis (Top 3):**
        {', '.join([f"{k}: {v}" for k, v in list(dados_analise.get('probabilidades_completas', {}).items())[:3]])}

        **WARNING:** This is a preliminary report generated by AI and must be validated by direct clinical evaluation.

        {aviso_p}
        """